### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by DeathCorps69** [jkuhlmann/gainput#2]
When running 'waf build' I get:
```
    Build failed
     -> task in 'listenersample' failed (exit status 1):
            {task 49072224L: cxx SampleFramework.cpp -> SampleFramework.cpp.1.o}
    ['G:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\BIN\\amd64\\CL.exe',
    '-O2',
    '/IC:\\Users\\Travis\\Desktop\\Gainput\\build\\release\\lib\\include',
    '/IC:\\Users\\Travis\\Desktop\\Gainput\\lib\\include',
    '/IG:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\INCLUDE',
    '/IG:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\ATLMFC\\INCLUDE',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\shared',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\um',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\winrt',
    '/DGAINPUT_LIB_BUILD=1',
    '/DNDEBUG=1',
    '',
    '..\\..\\samples\\samplefw\\SampleFramework.cpp',
    '/FC',
    '/c',
    '/Fo',
    'samples\\samplefw\\SampleFramework.cpp.1.o']
     -> task in 'recordingsample' failed (exit status 1):
            {task 49072672L: cxx SampleFramework.cpp -> SampleFramework.cpp.1.o}
    ['G:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\BIN\\amd64\\CL.exe',
    '-O2',
    '/IC:\\Users\\Travis\\Desktop\\Gainput\\build\\release\\lib\\include',
    '/IC:\\Users\\Travis\\Desktop\\Gainput\\lib\\include',
    '/IG:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\INCLUDE',
    '/IG:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\VC\\ATLMFC\\INCLUDE',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\shared',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\um',
    '/IC:\\Program Files (x86)\\Windows Kits\\8.0\\include\\winrt',
    '/DGAINPUT_LIB_BUILD=1',
    '/DNDEBUG=1',
    '',
    '..\\..\\samples\\samplefw\\SampleFramework.cpp',
    '/FC',
    '/c',
    '/Fo',
    'samples\\samplefw\\SampleFramework.cpp.1.o']
```
If I re-run it without deleting any folders it passes but I am getting linker errors when I try to use it.

**Comment by Zandare** [comment]
Build error: I am using Win8.1 and msvc 2013 x64 :(

D:\Downloads\gainput-0.9.0-beta>waf configure
Using python
Setting top to                           : D:\Downloads\gainput-0.9.0-beta
Setting out to                           : D:\Downloads\gainput-0.9.0-beta\build

Checking for 'msvc' (c++ compiler)       : C:\Program Files (x86)\Microsoft Visu
al Studio 12.0\VC\BIN\amd64\CL.exe
Checking for library Xinput9_1_0         : Traceback (most recent call last):
  File "D:\Downloads\gainput-0.9.0-beta\wscript", line 108, in configure
    uselib_store='XINPUT')
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Configure.py", line 224, in fun
    return f(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Tools\c_config.py", line 375, in check
    ret=self.run_c_code(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Configure.py", line 224, in fun
    return f(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Tools\c_config.py", line 459, in run_c_code
    bld.compile()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Build.py", line 186, in compile
    self.store()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Utils.py", line 386, in f
    ret=fun(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Build.py", line 162, in store
    x=cPickle.dumps(data,-1)
_pickle.PicklingError: Can't pickle <class 'waflib.Node.Context.__init__.<locals
>.node_class'>: attribute lookup Context.__init__.<locals>.node_class on waflib.
Node failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Scripting.py", line 153, in run_commands
    ctx=run_command(cmd_name)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Scripting.py", line 146, in run_command
    ctx.execute()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Configure.py", line 128, in execute
    super(ConfigurationContext,self).execute()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Context.py", line 128, in recurse
    user_function(self)
  File "D:\Downloads\gainput-0.9.0-beta\wscript", line 113, in configure
    uselib_store='XINPUT')
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Configure.py", line 224, in fun
    return f(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Tools\c_config.py", line 375, in check
    ret=self.run_c_code(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Configure.py", line 224, in fun
    return f(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Tools\c_config.py", line 459, in run_c_code
    bld.compile()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Build.py", line 186, in compile
    self.store()
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Utils.py", line 386, in f
    ret=fun(*k,**kw)
  File "D:\Downloads\gainput-0.9.0-beta\waf3-1.7.11-edc6ccb516c5e3f9b892efc9f53a
610f\waflib\Build.py", line 162, in store
    x=cPickle.dumps(data,-1)
_pickle.PicklingError: Can't pickle <class 'waflib.Node.Context.__init__.<locals
>.node_class'>: attribute lookup Context.__init__.<locals>.node_class on waflib.
Node failed

D:\Downloads\gainput-0.9.0-beta>

**Comment by jkuhlmann** [comment]
Unfortunately, I haven't gotten around to creating a new release recently, but there have been a lot of changes to the master branch. Among others, the build system has been switched to CMake which might do a better job than Waf in this case.
Is there any chance you could pull the master branch and try that out?

**Comment by Zandare** [comment]
Thank you. It worked.
